function base64(content) {
    return window.btoa(unescape(encodeURIComponent(content)));
}
/*
*@tableId: table的Id
*@fileName: 要生成excel文件的名字（不包括后缀，可随意填写）
*/
function tableToExcel(tableID, fileName) {
    var subject = document.getElementById('TextBox1').value, reaforca = document.getElementById('TextBox2').value, occurSite = document.getElementById('TextBox3').value, occurTime = document.getElementById('TextBox4').value, occurQty = document.getElementById('TextBox5').value, raiseDate = document.getElementById('TextBox6').value, customer = document.getElementById('TextBox7').value, partNum = document.getElementById('TextBox8').value, QtvIns = document.getElementById('TextBox9').value, raiseBy = document.getElementById('TextBox86').value;
    var supplier = document.getElementById('TextBox10').value, partName = document.getElementById('TextBox11').value, QtvRei = document.getElementById('TextBox12').value, dueDate = document.getElementById('TextBox13').value;
    var table = document.getElementById(tableID);
    var excelCss = '<style type="text/css">	* {	padding: 0px;margin: 0px;}	table {margin-bottom: 100px;margin-top: 50px;width: 70 %;border: solid #000000;border-width: 2px 2px 2px 2px;margin-left: auto;margin-right: auto;}	table tr {border-width: 1px;height: 38px;} table tr td {border: solid #000000;border-width: 1px;font-size: 12px;font-family: Serif} .tr1 {width: 100px;height: 76px	}.tr2 {height: 38px;}.td2 {width: 200px	}}</style >';
    var excelFile = "<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:x='urn:schemas-microsoft-com:office:excel' xmlns='http://www.w3.org/TR/REC-html40'>";
    excelFile += "<head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]-->"
		+ excelCss + "</head > ";
    excelFile += "<body><table>";
    excelFile += '<tr><th colspan="12" style="font-size:30px;font-family:Serif">8D报告</th></tr>'
		+ ' <tr><td colspan="12" style="font-size:15px;text-align:center">（CA report in 8D format) </td></tr>'
		+ '	<tr>'
		+ '		<td colspan="1"  style="text-align:center" class="tr1">主题<br />(Subject)</td>'
		+ '		<td colspan="5"  style="text-align:center" >' + subject + '</td>'
		+ '		<td colspan="1"  style="text-align:center" class="tr1">投诉类型<br />(Rea For CA)</td>'
		+ '		<td colspan="5"  style="text-align:center">' + reaforca + '</td>'
		+ '	</tr>'
		+ '	<tr>'
		+ '		<td colspan="1" style="text-align:center" class="tr1">发生地点<br />(Occurred Site)</td>'
		+ '		<td colspan="2"  style="text-align:center" class="td2">' + occurSite + '</td>'
		+ '		<td colspan="1" style="text-align:center" class="tr1">发生时间<br />(Occurred Time)</td>'
		+ '		<td colspan="2"  style="text-align:center" class="td2">' + occurTime + '</td>'
		+ '		<td colspan="1" style="text-align:center" class="tr1">总批量数<br />(Occurred Qty)</td>'
		+ '		<td colspan="2"  style="text-align:center" class="td2">' + occurQty + '</td>'
		+ '		<td colspan="1" style="text-align:center" class="tr1">提出日<br />(Date Raised)</td>'
		+ '		<td colspan="2"  style="text-align:center" class="td2">' + raiseDate + '</td>'
		+ '	</tr>'
		+ '	<tr>'
		+ '		<td colspan="1" style="text-align:center" class="tr1">客户<br />(Customer)</td>'
		+ '		<td colspan="2"  style="text-align:center" >' + customer + '</td>'
		+ '		<td colspan="1" style="text-align:center" class="tr1">产品编号<br />(Part Number)</td>'
		+ '		<td colspan="2"  style="text-align:center" >' + partNum + '</td>'
		+ '		<td colspan="1" style="text-align:center" class="tr1">检验数<br />(Qtv Ins)</td>'
		+ '		<td colspan="2"  style="text-align:center" >' + QtvIns + '</td>'
		+ '		<td colspan="1" style="text-align:center" class="tr1">提出人员<br />(Raised by)</td>'
		+ '		<td colspan="2"  style="text-align:center" >' + raiseBy + '</td>'
		+ '	</tr>'
		+ '	<tr>'
		+ '		<td colspan="1" style="text-align:center" class="tr1">供应商厂商<br />(Supplier)</td>																																																   '
		+ '		<td colspan="2"  style="text-align:center" >' + supplier + '</td>																															'
		+ '		<td colspan="1" style="text-align:center" class="tr1">产品名称<br />(PartName)</td>																																																		'
		+ '		<td colspan="2"  style="text-align:center" >' + partName + '</td>																															'
		+ '		<td colspan="1" style="text-align:center" class="tr1">不良数<br />(Qtv Rei)</td>																																																		 '
		+ '		<td colspan="2"  style="text-align:center" >' + QtvRei + '</td>																															'
		+ '		<td colspan="1" style="text-align:center" class="tr1">要求完成日期<br />(Due Date)</td>																																																  '
		+ '		<td colspan="2"  style="text-align:center" >' + dueDate + '</td>																																'
		+ '	</tr>																																																																						'
		+ '	<tr>																																																																						'
		+ '		<td colspan="12" style="background-color:rgb(153,204,255)">1、小组成员(Discipline  1.Team Members)</td>																																												   '
		+ '	</tr>																																																																						'
		+ '	<tr>																																																																						'
		+ '		<td colspan="1" class="tr2">部门(Dept)：</td>																																																											 '
		+ '		<td colspan="2"  style="text-align:center" >QA</td>																																																										'
		+ '		<td colspan="1" style="text-align:center" class="tr2">IQC</td>																																																							'
		+ '		<td colspan="2"  style="text-align:center" >生产</td>																																																									  '
		+ '		<td colspan="1" style="text-align:center" class="tr2">工程</td>																																																						  '
		+ '		<td colspan="2"  style="text-align:center" >开发</td>																																																									  '
		+ '		<td colspan="1" style="text-align:center" class="tr2">采购</td>																																																						  '
		+ '		<td colspan="2"  style="text-align:center" >业务</td>																																																									  '
		+ '	</tr>'
		+ '	<tr>'
		+ '		<td colspan="1" class="tr2">姓名(Name)：</td>																																																											 '
		+ '		<td colspan="2"  style="text-align:center" ></td>																															'
		+ '		<td colspan="1" style="text-align:center" class="tr2"></td>																												'
		+ '		<td colspan="2"  style="text-align:center" ></td>																															'
		+ '		<td colspan="1" style="text-align:center" class="tr2"></td>																												'
		+ '		<td colspan="2"  style="text-align:center" ></td>																															'
		+ '		<td colspan="1" style="text-align:center" class="tr2"></td>																												'
		+ '		<td colspan="2"  style="text-align:center" ></td>																															'
		+ '	</tr>																																																																						'
		+ '	<tr>																																																																						'
		+ '		<td colspan="12" style="background-color:rgb(153,204,255)">2、问题描述(Discipline  2. Problem Description)</td>																																										   '
		+ '	</tr>																																																																						'
		+ '	<tr>																																																																						'
		+ '		<td colspan="12" class="tr2"></td>																																			'
		+ '	</tr>																																																																						'
		+ '	<tr>																																																																						'
		+ '		<td colspan="4">起草Prepared By：</td>																																										 '
		+ '		<td colspan="4">审核Approved By：</td>																																										 '
		+ '		<td colspan="4">完成日期Completed Date：</td>																																							   '
		+ '	</tr>																																																																						'
		+ '	<tr>																																																																						'
		+ '		<td colspan="12" style="background-color:rgb(153,204,255)">3、即日纠正措施(Discipline  3. Immediate Containment Actions)</td>																																							 '
		+ '	</tr>																																																																						'
		+ '	<tr>																																																																						'
		+ '		<td colspan="1" style="text-align:center">NO.</td>																																																										'
		+ '		<td colspan="8" style="text-align:center">暂时补救的纠正措施(Immediate Containment Actions)</td>																																														   '
		+ '		<td colspan="1" style="text-align:center">负责人</td>																																																									 '
		+ '		<td colspan="2" style="text-align:center">日期</td>																																																									  '
		+ '	</tr>																																																																						'
		+ '	<tr>																																																																						'
		+ '		<td colspan="1" style="text-align:center">																																																												'
		+ '		<td colspan="8" style="text-align:center"></td>																															'
		+ '		<td colspan="1" style="text-align:center"></td>																															'
		+ '		<td colspan="2" style="text-align:center"></td>																																	'
		+ '	</tr>																																																																						'
		+ '	<tr>																																																																						'
		+ '		<td colspan="1" style="text-align:center">																																																												'
		+ '		</td>																																																																					'
		+ '		<td colspan="8" style="text-align:center"></td>															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center"></td>																																														'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center"></td>																																														'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="6" >审核 Approved By：</td>																																									 '
			+ '		<td colspan="6" >审核日期 Approved Date：</td>																																			   '
			+ '	</tr>																																																																						'
			+ '																																																																								'
			+ '	<tr>																																																																						'
			+ '		<td colspan="12" style="background-color:rgb(153,204,255)">4、明确和核实根本原因(Discipline  4.Define and Verify Root Causes)</td>																																					  '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="12" style="height:114px"></td>																													'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="4">起草Prepared By：</td>																																										 '
			+ '		<td colspan="4">审核Approved By：</td>																																										 '
			+ '		<td colspan="4">完成日期Completed Date：</td>																																			   '
			+ '	</tr>																																																																						'
			+ '																																																																								'
			+ '	<tr>																																																																						'
			+ '		<td colspan="12" style="background-color:rgb(153,204,255)">5、永久性纠正措施(Discipline  5. Permanent Corrective Actions)</td>																																							'
			+ '	</tr>																																																																						'
			+ '																																																																								'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center">NO.</td>																																																										'
			+ '		<td colspan="8" style="text-align:center">纠正措施(permanent Corrective Actions)</td>																																																	'
			+ '		<td colspan="1" style="text-align:center">确认人</td>																																																									 '
			+ '		<td colspan="2" style="text-align:center">日期</td>																																																									  '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center"></td>																																														'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center"></td>																																														'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center"></td>																																														'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center"></td>																																														'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="6" >审核 Approved By：</td>																																									 '
			+ '		<td colspan="6" >审核日期 Approved Date：</td>																																							   '
			+ '	</tr>																																																																						'
			+ '																																																																								'
			+ '	<tr>																																																																						'
			+ '		<td colspan="12" style="background-color:rgb(153,204,255)">6、纠正措施效果验证(Discipline  6.Verification of Effectiveness)</td>																																						   '
			+ '	</tr>																																																																						'
			+ '																																																																								'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center">NO.</td>																																																										'
			+ '		<td colspan="8" style="text-align:center">效果验证(Verification of  Effectiveness)</td>																																																	'
			+ '		<td colspan="1" style="text-align:center">确认人</td>																																																									 '
			+ '		<td colspan="2" style="text-align:center">日期</td>																																																									  '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center"></td>																																														'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center"></td>																																														'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center"></td>																																														'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center"></td>																																														'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="6" >审核 Approved By：</td>																																									 '
			+ '		<td colspan="6" >审核日期 Approved Date：</td>																																			   '
			+ '	</tr>																																																																						'
			+ '																																																																								'
			+ '	<tr>																																																																						'
			+ '		<td colspan="12" style="background-color:rgb(153,204,255)">7、预防再现措施(Discipline  7.Prevent Recurrence)</td>																																										 '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center">NO.</td>																																																										'
			+ '		<td colspan="8" style="text-align:center">预防再现措施(Prevent Recurrence)</td>																																																		  '
			+ '		<td colspan="1" style="text-align:center">负责人</td>																																																									 '
			+ '		<td colspan="2" style="text-align:center">日期</td>																																																									  '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center">'
			+ '		</td>																																																																					'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center" class="tr2">																																																									'
			+ '		</td>																																																																					'
			+ '		<td colspan="8" style="text-align:center" class="tr2"></td>																												'
			+ '		<td colspan="1" style="text-align:center" class="tr2"></td>																												'
			+ '		<td colspan="2" style="text-align:center" class="tr2"></td>																														'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center">																																																												'
			+ '		</td>																																																																					'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="1" style="text-align:center">																																																												'
			+ '		</td>																																																																					'
			+ '		<td colspan="8" style="text-align:center"></td>																															'
			+ '		<td colspan="1" style="text-align:center"></td>																															'
			+ '		<td colspan="2" style="text-align:center"></td>																																	'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="6" >审核 Approved By：</td>																																									 '
			+ '		<td colspan="6" >审核日期 Approved Date：</td>																																			   '
			+ '	</tr>																																																																						'
			+ '																																																																								'
			+ '	<tr>																																																																						'
			+ '		<td colspan="12" style="background-color:rgb(153,204,255)">8、客户确认及评价(Discipline 8.Customer satisfaction degree)</td>																																							'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="12" style="border-bottom-width:2px;padding:0px" class="auto-style1"></td>																		'
			+ '	</tr>																																																																						'
			+ '																																																																								'
			+ '	<tr>																																																																						'
			+ '		<th colspan="12" style="border:;border-width:2px" >不良根本原因类型（勾选项，可多选）</th>																																															   '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
		+ '			<th colspan="2" style="border:1px solid">人</th>																																																										   '
			+ '		<th colspan="2" style="border:1px solid">机</th>																																																										   '
			+ '		<th colspan="2" style="border:1px solid">料</th>																																																										   '
			+ '		<th colspan="2" style="border:1px solid">法</th>																																																										   '
			+ '		<th colspan="2" style="border:1px solid">环</th>																																																										   '
			+ '		<th colspan="2" style="border:1px solid">测</th>																																																										   '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
		+ '			<td colspan="2" style="text-align:center">新员工<input type="checkbox" /></td>																																							 '
		+ '		<td colspan="2" style="text-align:center">设备能力不足<input type="checkbox" /></td>																																					  '
		+ '		<td colspan="2" style="text-align:center">原材料不良<input type="checkbox" /></td>																																						   '
		+ '		<td colspan="2" style="text-align:center">设计问题<input type="checkbox" /></td>																																							'
		+ '		<td colspan="2" style="text-align:center">生产环境不良<input type="checkbox" /></td>																																					  '
		+ '		<td colspan="2" style="text-align:center">缺测量设备 <input type="checkbox" /></td>																																						   '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
		+ '		<td colspan="2" style="text-align:center">临时工<input type="checkbox" /></td>																																							 '
		+ '		<td colspan="2" style="text-align:center">设备故障<input type="checkbox" /></td>																																							'
		+ '		<td colspan="2" style="text-align:center">物料保存不良<input type="checkbox" /></td>																																					  '
		+ '		<td colspan="2" style="text-align:center">工艺问题<input type="checkbox" /></td>																																							'
		+ '		<td colspan="2" style="text-align:center">仓储环境不良<input type="checkbox" /></td>																																					  '
		+ '		<td colspan="2" style="text-align:center">量具能力不足<input type="checkbox" /></td>																																					  '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
		+ '		<td colspan="2" style="text-align:center">顶岗<input type="checkbox" /></td>																																							  '
		+ '		<td colspan="2" style="text-align:center">设备PM不足<input type="checkbox" /></td>																																						'
		+ '		<td colspan="2" style="text-align:center">混料<input type="checkbox" /></td>																																							  '
		+ '		<td colspan="2" style="text-align:center">仓储问题<input type="checkbox" /></td>																																							'
		+ '		<td colspan="2" style="text-align:center">新车间<input type="checkbox" /></td>																																							 '
		+ '		<td colspan="2" style="text-align:center">测量方法问题<input type="checkbox" /></td>																																					  '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
		+ '		<td colspan="2" style="text-align:center">其它<input type="checkbox" /></td>																																							  '
		+ '		<td colspan="2" style="text-align:center">模具问题<input type="checkbox" /></td>																																							'
		+ '		<td colspan="2" style="text-align:center">缺料<input type="checkbox" /></td>																																							  '
		+ '		<td colspan="2" style="text-align:center">运输问题<input type="checkbox" /></td>																																							'
		+ '		<td colspan="2" style="text-align:center">其它<input type="checkbox" /></td>																																							  '
		+ '		<td colspan="2" style="text-align:center">其它<input type="checkbox" /></td>																																							  '
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="2" style="text-align:center"></td>																																																											'
		+ '		<td colspan="2" style="text-align:center">新设备<input type="checkbox" /></td>																																							 '
		+ '		<td colspan="2" style="text-align:center">其它<input type="checkbox" /></td>																																							  '
		+ '		<td colspan="2" style="text-align:center">变更管理问题<input type="checkbox" /></td>																																					  '
			+ '		<td colspan="2" style="text-align:center"></td>																																																											'
			+ '		<td colspan="2" style="text-align:center"></td>																																																											'
			+ '	</tr>																																																																						'
			+ '	<tr>																																																																						'
			+ '		<td colspan="2" style="text-align:center"></td>																																																											'
		+ '		<td colspan="2" style="text-align:center">其它<input type="checkbox" /></td>																																							  '
			+ '		<td colspan="2" style="text-align:center"></td>																																																											'
		+ '		<td colspan="2" style="text-align:center">其它<input type="checkbox" /></td>																																							  '
			+ '		<td colspan="2" style="text-align:center"></td>																																																											'
			+ '		<td colspan="2" style="text-align:center"></td>																																																											'
			+ '	</tr>'

			+ '	<tr>'
			+ '		<td colspan="1" >备注(Memo)</td>'
			+ '		<td colspan="11" style="height:72px"></td>'
			+ '</tr>';
    excelFile += "</table></body>";
    excelFile += "</html>";
    var link = "data:application/vnd.ms-excel;base64," + base64(excelFile);
    var a = document.createElement("a");
    a.download = fileName + ".xlsx";
    a.href = link;
    a.click();
}